Lazy detect transport
ros-visualization/rqt_image_view pull request #70
Opened 2022-05-18 09:47 UTC by furushchev

Fixes https://github.com/ros-visualization/rqt_image_view/issues/69

If it cannot be detectable which transport should be used when a topic is selected, `rqt_image_view` subscribes the topic using `topic_tools::ShapeShifter` and then determine the transport when the first message arrived.

2022-05-22 23:51 UTC, furushchev commented
@mabelzhang Kindly ping to the maintainer

2023-08-29 18:50 UTC, furushchev commented
@MatthijsBurgh @wjwwood Kindly ping to the maintainer.

2023-08-30 07:28 UTC, MatthijsBurgh requested changes

2023-08-30 07:28 UTC, MatthijsBurgh commented on package.xml
> +  <depend>topic_tools</depend>
Depend tags are often on top. Set of the same tag are always seperated by an empty line.

2023-08-30 07:29 UTC, MatthijsBurgh reviewed
As ROS1 is not getting a new release. I don't want to introduce such a big new feature.

2025-04-23 18:19 UTC, sloretz commented
Thank you for the PR!

Unfortunately I don't think we should merge this one.

[ROS Noetic will reach end-of-life on May 31st, 2025](https://discourse.ros.org/t/ros-noetic-end-of-life-may-31-2025/43160). Every change comes with a risk of introducing regressions, and there isn't much time left to fix them. I'm closing pull requests that add features so that the remaining time is allocated towards bug fixes and compatibility with newer Ubuntu distros.

2025-04-23 18:19 UTC, closed without merging